# Generated by Django 5.2.14 on 2026-05-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('eyebrow', models.CharField(blank=True, default='Signature category', max_length=80, verbose_name='Надпись')),
                ('icon', models.CharField(default='cup', help_text='cup, beans, leaf, snow, croissant, ice', max_length=40, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('price_label', models.CharField(blank=True, default='TMT', help_text='Валюта/единица — выводится рядом с числом', max_length=20, verbose_name='Подпись к цене')),
                ('volume', models.CharField(blank=True, default='', max_length=40, verbose_name='Объём / порция')),
                ('tags', models.CharField(blank=True, default='', help_text='Через запятую: айс, ягодный, авторский', max_length=200, verbose_name='Теги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drinks/', verbose_name='Изображение')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='menu.drinkcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
    ]
