# Generated by Django 5.2.14 on 2026-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='description_tk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='drink',
            name='name_tk',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='drink',
            name='price_label_en',
            field=models.CharField(blank=True, default='TMT', help_text='Валюта/единица — выводится рядом с числом', max_length=20, null=True, verbose_name='Подпись к цене'),
        ),
        migrations.AddField(
            model_name='drink',
            name='price_label_ru',
            field=models.CharField(blank=True, default='TMT', help_text='Валюта/единица — выводится рядом с числом', max_length=20, null=True, verbose_name='Подпись к цене'),
        ),
        migrations.AddField(
            model_name='drink',
            name='price_label_tk',
            field=models.CharField(blank=True, default='TMT', help_text='Валюта/единица — выводится рядом с числом', max_length=20, null=True, verbose_name='Подпись к цене'),
        ),
        migrations.AddField(
            model_name='drink',
            name='short_description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='short_description_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='short_description_tk',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='tags_en',
            field=models.CharField(blank=True, default='', help_text='Через запятую: айс, ягодный, авторский', max_length=200, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='drink',
            name='tags_ru',
            field=models.CharField(blank=True, default='', help_text='Через запятую: айс, ягодный, авторский', max_length=200, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='drink',
            name='tags_tk',
            field=models.CharField(blank=True, default='', help_text='Через запятую: айс, ягодный, авторский', max_length=200, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='drink',
            name='volume_en',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Объём / порция'),
        ),
        migrations.AddField(
            model_name='drink',
            name='volume_ru',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Объём / порция'),
        ),
        migrations.AddField(
            model_name='drink',
            name='volume_tk',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Объём / порция'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='description_tk',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='eyebrow_en',
            field=models.CharField(blank=True, default='Signature category', max_length=80, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='eyebrow_ru',
            field=models.CharField(blank=True, default='Signature category', max_length=80, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='eyebrow_tk',
            field=models.CharField(blank=True, default='Signature category', max_length=80, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='name_tk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
    ]
