# Generated by Django 5.2.14 on 2026-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, default='', max_length=240, verbose_name='Описание')),
                ('icon', models.CharField(default='cup', help_text='cup, wifi, leaf, clock, heart, beans', max_length=40, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Specialty coffee', max_length=80, verbose_name='Надпись сверху')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок')),
                ('cta_text', models.CharField(blank=True, default='Смотреть меню', max_length=60, verbose_name='Текст ссылки')),
                ('cta_url', models.CharField(blank=True, default='/menu/', max_length=200, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Hero · слайд',
                'verbose_name_plural': 'Hero · слайды',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Автор')),
                ('role', models.CharField(blank=True, default='Гость', max_length=160, verbose_name='Подпись')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='Оценка')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Аватар')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Отображать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Yarcoffee', max_length=120, verbose_name='Название бренда')),
                ('tagline', models.CharField(default='Маленькая кофейня с большим сердцем', max_length=255, verbose_name='Слоган')),
                ('phone', models.CharField(default='+993 65 722525', max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(default='hello@yarcoffee.tm', max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(default='Ашхабад, ул. Туркменбаши', max_length=255, verbose_name='Адрес')),
                ('address_secondary', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес (доп.)')),
                ('working_hours', models.CharField(default='Каждый день · 07:30 — 22:45', max_length=120, verbose_name='Часы работы')),
                ('instagram', models.URLField(default='https://www.instagram.com/yarcoffee.tm/', verbose_name='Instagram')),
                ('tiktok', models.URLField(default='https://www.tiktok.com/@yarcoffee.tm', verbose_name='TikTok')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, default='', verbose_name='WhatsApp')),
                ('map_embed_url', models.URLField(blank=True, default='https://www.openstreetmap.org/export/embed.html?bbox=58.36%2C37.93%2C58.40%2C37.96&layer=mapnik', verbose_name='Карта (embed URL)')),
                ('footer_note', models.TextField(default='Crafted with love. Brewed for the neighbourhood.', verbose_name='Подпись в футере')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Our story', max_length=80, verbose_name='Надпись сверху')),
                ('title', models.CharField(default='Маленькая кофейня с большим сердцем', max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='story/', verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'История · блок',
                'verbose_name_plural': 'История · блоки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('role', models.CharField(default='Barista', max_length=120, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, default='', verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Команда · участник',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', 'id'],
            },
        ),
    ]
