# Generated by Django 5.2.14 on 2026-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_tk',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_tk',
            field=models.CharField(max_length=120, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_en',
            field=models.CharField(blank=True, default='Смотреть меню', max_length=60, null=True, verbose_name='Текст ссылки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_ru',
            field=models.CharField(blank=True, default='Смотреть меню', max_length=60, null=True, verbose_name='Текст ссылки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_tk',
            field=models.CharField(blank=True, default='Смотреть меню', max_length=60, null=True, verbose_name='Текст ссылки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='eyebrow_en',
            field=models.CharField(default='Specialty coffee', max_length=80, null=True, verbose_name='Надпись сверху'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='eyebrow_ru',
            field=models.CharField(default='Specialty coffee', max_length=80, null=True, verbose_name='Надпись сверху'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='eyebrow_tk',
            field=models.CharField(default='Specialty coffee', max_length=80, null=True, verbose_name='Надпись сверху'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_tk',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_tk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_tk',
            field=models.CharField(max_length=120, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='review',
            name='role_en',
            field=models.CharField(blank=True, default='Гость', max_length=160, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='review',
            name='role_ru',
            field=models.CharField(blank=True, default='Гость', max_length=160, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='review',
            name='role_tk',
            field=models.CharField(blank=True, default='Гость', max_length=160, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_tk',
            field=models.TextField(null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(default='Ашхабад, ул. Туркменбаши', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(default='Ашхабад, ул. Туркменбаши', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_secondary_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес (доп.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_secondary_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес (доп.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_secondary_tk',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес (доп.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_tk',
            field=models.CharField(default='Ашхабад, ул. Туркменбаши', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_en',
            field=models.CharField(default='Yarcoffee', max_length=120, null=True, verbose_name='Название бренда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_ru',
            field=models.CharField(default='Yarcoffee', max_length=120, null=True, verbose_name='Название бренда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_tk',
            field=models.CharField(default='Yarcoffee', max_length=120, null=True, verbose_name='Название бренда'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_note_en',
            field=models.TextField(default='Crafted with love. Brewed for the neighbourhood.', null=True, verbose_name='Подпись в футере'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_note_ru',
            field=models.TextField(default='Crafted with love. Brewed for the neighbourhood.', null=True, verbose_name='Подпись в футере'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_note_tk',
            field=models.TextField(default='Crafted with love. Brewed for the neighbourhood.', null=True, verbose_name='Подпись в футере'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(default='Маленькая кофейня с большим сердцем', max_length=255, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ru',
            field=models.CharField(default='Маленькая кофейня с большим сердцем', max_length=255, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_tk',
            field=models.CharField(default='Маленькая кофейня с большим сердцем', max_length=255, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_en',
            field=models.CharField(default='Каждый день · 07:30 — 22:45', max_length=120, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_ru',
            field=models.CharField(default='Каждый день · 07:30 — 22:45', max_length=120, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_tk',
            field=models.CharField(default='Каждый день · 07:30 — 22:45', max_length=120, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='body_tk',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='eyebrow_en',
            field=models.CharField(default='Our story', max_length=80, null=True, verbose_name='Надпись сверху'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='eyebrow_ru',
            field=models.CharField(default='Our story', max_length=80, null=True, verbose_name='Надпись сверху'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='eyebrow_tk',
            field=models.CharField(default='Our story', max_length=80, null=True, verbose_name='Надпись сверху'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='image_alt_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='image_alt_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='image_alt_tk',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='title_en',
            field=models.CharField(default='Маленькая кофейня с большим сердцем', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='title_ru',
            field=models.CharField(default='Маленькая кофейня с большим сердцем', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='storysection',
            name='title_tk',
            field=models.CharField(default='Маленькая кофейня с большим сердцем', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_tk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_tk',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(default='Barista', max_length=120, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(default='Barista', max_length=120, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_tk',
            field=models.CharField(default='Barista', max_length=120, null=True, verbose_name='Должность'),
        ),
    ]
