# Generated by Django 5.2.14 on 2026-05-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_description_en_feature_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26888.893790685728!2d58.35219072492952!3d37.90780940000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f6ffd00329d28e1%3A0x6f327a51b8e8efd0!2s%C3%9DARcoffee!5e1!3m2!1sru!2sus!4v1779867304819!5m2!1sru!2sus', help_text='Embed-ссылка из Google Maps → Поделиться → Встроить карту.', max_length=500, verbose_name='Карта (embed URL)'),
        ),
    ]
