# Generated by Django 5.2.14 on 2026-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=160, verbose_name='Подпись')),
                ('category', models.CharField(choices=[('drinks', 'Напитки'), ('interior', 'Интерьер'), ('people', 'Люди'), ('moments', 'Моменты')], default='moments', max_length=32, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('span', models.CharField(choices=[('normal', '1×1'), ('tall', '1×2'), ('wide', '2×1'), ('large', '2×2')], default='normal', max_length=20, verbose_name='Размер плитки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Галерея · изображение',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
