# Generated by Django 5.2.14 on 2026-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_tk',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Подпись'),
        ),
    ]
